#DATA UPLOADING AND CLEANING 
#DECODING METHANE CONCENTRATIONS IN ALBERTA OIL SANDS: A MACHINE LEARNING EXPLORATION"

Run 1._start_up_code.R 



####DATA UPLOAD AND CLEANING####


#FOR CLEANED 2019_2022 DATA#


Data_Path <- "/Users/milsbeary/Desktop/Miles NSERC Alliance Missions /Air Quality Monotoring of Polutents/Land Station/FINAL_STUDY_DS/Data/Cleaned" #Define data path

hour_mild_files <- c(list.files(path=Data_Path, pattern="*.csv", full.names=TRUE)) #Get list of all csv files in the folder
hour_mild_files #See list, make sure it is different from the first


#Anzac
Anz_upload <- data.frame(read.csv(hour_mild_files[1], check.names=FALSE)) 
colnames(Anz_upload) #Taking a look at our colnames
unique(Anz_upload$name) #Make sure right sation is uploaded
#Anz_upload$cloud_fraction

#Some land cover
Anz_slc <- as.data.frame(Anz_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3", "Land_Cover_majority"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Anz_slc)
summary(Anz_slc)	
colnames(Anz_slc)

#No land cover 	
Anz_nlc <- as.data.frame(Anz_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow", "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Anz_nlc)
summary(Anz_nlc)	
colnames(Anz_nlc)

#Land cover majority
Anz_lcm <- as.data.frame(Anz_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Anz_lcm)
summary(Anz_lcm)	
colnames(Anz_lcm)


#Athabasca 
Ath_upload <- data.frame(read.csv(hour_mild_files[2], check.names=FALSE)) 
#Anz_upload$Station = rep(stat_nms[1], nrow(Anz_upload)) #Adding the station n name column
colnames(Ath_upload) #Taking a look at our colnames
unique(Ath_upload$name) #Make sure right sation is uploaded

#Some land cover
Ath_slc <- as.data.frame(Ath_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ath_slc)
summary(Ath_slc)	
colnames(Ath_slc)

#No land cover 	
Ath_nlc <- as.data.frame(Ath_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow",  "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ath_nlc)
summary(Ath_nlc)	
colnames(Ath_nlc)

#Land cover majority
Ath_lcm <- as.data.frame(Ath_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Ath_lcm)
summary(Ath_lcm)	
colnames(Ath_lcm)	


#Berta
Ber_upload <- data.frame(read.csv(hour_mild_files[3], check.names=FALSE)) 
colnames(Ber_upload) #Taking a look at our colnames
unique(Ber_upload$name) #Make sure right sation is uploaded

#Some land cover
Ber_slc <- as.data.frame(Ber_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Ber_slc)
summary(Ber_slc)
colnames(Ber_slc)

#No land cover 	
Ber_nlc <- as.data.frame(Ber_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow", "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ber_nlc)
summary(Ber_nlc)	
colnames(Ber_nlc)

#Land cover majority
Ber_lcm <- as.data.frame(Ber_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Ber_lcm)
summary(Ber_lcm)	
colnames(Ber_lcm)	


#Buffalo
Buf_upload <- data.frame(read.csv(hour_mild_files[4], check.names=FALSE)) 
colnames(Buf_upload) #Taking a look at our colnames
unique(Buf_upload$name) #Make sure right sation is uploaded

#Some land cover
Buf_slc <- as.data.frame(Buf_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Buf_slc)
summary(Buf_slc)
colnames(Buf_slc)

#No land cover
Buf_nlc <- as.data.frame(Buf_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Buf_nlc)
summary(Buf_nlc)	
colnames(Buf_nlc)

#Land cover majority
Buf_lcm <- as.data.frame(Buf_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			  mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			  mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Buf_lcm)
summary(Buf_lcm)	
colnames(Buf_lcm)	


#Conklin 
Con_upload <- data.frame(read.csv(hour_mild_files[5], check.names=FALSE)) 
colnames(Con_upload) #Taking a look at our colnames
unique(Con_upload$name) #Make sure right sation is uploaded

#Some land cover
Con_slc <- as.data.frame(Con_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Con_slc)
summary(Con_slc)
colnames(Con_slc)

#No land cover 	
Con_nlc <- as.data.frame(Con_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Con_nlc)
summary(Con_nlc)	
colnames(Con_nlc)

#Land cover majority
Con_lcm <- as.data.frame(Con_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Con_lcm)
summary(Con_lcm)	
colnames(Con_lcm)	


#Janvier
Jan_upload <- data.frame(read.csv(hour_mild_files[6], check.names=FALSE)) 
colnames(Jan_upload) #Taking a look at our colnames
unique(Jan_upload$name) #Make sure right sation is uploaded

#Some land cover
Jan_slc <- as.data.frame(Jan_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Jan_slc)
summary(Jan_slc)
colnames(Jan_slc)

#No land cover 	
Jan_nlc <- as.data.frame(Jan_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Jan_nlc)
summary(Jan_nlc)	
colnames(Jan_nlc)

#Land cover majority
Jan_lcm <- as.data.frame(Jan_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Jan_lcm)
summary(Jan_lcm)	
colnames(Jan_lcm)	


#Lower camp
Low_upload <- data.frame(read.csv(hour_mild_files[7], check.names=FALSE)) 
colnames(Low_upload) #Taking a look at our colnames
unique(Low_upload$name) #Make sure right sation is uploaded

#Some land cover
Low_slc <- as.data.frame(Low_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Low_slc)
summary(Low_slc)
colnames(Low_slc)

#No land cover 	
Low_nlc <- as.data.frame(Low_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Low_nlc)
summary(Low_nlc)	
colnames(Low_nlc)

#Land cover majority
Low_lcm <- as.data.frame(Low_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Low_nlc)
summary(Low_lcm)	
colnames(Low_lcm)


#Mannix 
Man_upload <- data.frame(read.csv(hour_mild_files[8], check.names=FALSE)) 
#Anz_upload$Station = rep(stat_nms[1], nrow(Anz_upload)) #Adding the station n name column
colnames(Man_upload) #Taking a look at our colnames
unique(Man_upload$name) #Make sure right sation is uploaded

#Some land cover
Man_slc <- as.data.frame(Man_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)#%>%
			 # #na.omit() #Remove all NA values generated by the Zs	
head(Man_slc)
summary(Man_slc)
colnames(Man_slc)

#No land cover 	
Man_nlc <- as.data.frame(Man_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Man_nlc)
summary(Man_nlc)	
colnames(Man_nlc)

#Land cover majority
Man_lcm <- as.data.frame(Man_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Man_lcm)
summary(Man_lcm)	
colnames(Man_lcm)	


#Mildred 
Mil_upload <- data.frame(read.csv(hour_mild_files[9], check.names=FALSE)) 
colnames(Mil_upload) #Taking a look at our colnames
unique(Mil_upload$name) #Make sure right sation is uploaded

#Some land cover
Mil_slc <- as.data.frame(Mil_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Mil_slc)
summary(Mil_slc)
colnames(Mil_slc)

#No land cover 	
Mil_nlc <- as.data.frame(Mil_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Mil_nlc)
summary(Mil_nlc)	
colnames(Mil_nlc)

#Land cover majority
Mil_lcm <- as.data.frame(Mil_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			  mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Mil_lcm)
summary(Mil_lcm)	
colnames(Mil_lcm)	


#Patricia 
Pat_upload <- data.frame(read.csv(hour_mild_files[10], check.names=FALSE)) 
colnames(Pat_upload) #Taking a look at our colnames
unique(Pat_upload$name) #Make sure right sation is uploaded

#Some land cover
Pat_slc <- as.data.frame(Pat_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Pat_slc)
summary(Pat_slc)
colnames(Pat_slc)

#No land cover 	
Pat_nlc <- as.data.frame(Pat_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Pat_nlc)
summary(Pat_nlc)	
colnames(Pat_nlc)

#Land cover majority
Pat_lcm <- as.data.frame(Pat_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Pat_lcm)
summary(Pat_lcm)	
colnames(Pat_lcm)	


#Stacked with gas 
Sta_upload <- data.frame(read.csv(hour_mild_files[11], check.names=FALSE))%>%filter(yyyy.MM.dd.HH.mm < "2023-01-01 00:00") #Make sure we are in the correct data range
colnames(Sta_upload) #Taking a look at our colnames
unique(Sta_upload$name) #Make sure right sation is uploaded
summary(Sta_upload)


#Some land cover
Sta_slc <- as.data.frame(Sta_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values generated by the Zs	
head(Sta_slc)
summary(Sta_slc)
colnames(Sta_slc)

#No land cover 	
Sta_nlc <- as.data.frame(Sta_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values generated by the Zs
head(Sta_nlc)
summary(Sta_nlc)	
colnames(Sta_nlc)

#Land cover majority
Sta_lcm <- as.data.frame(Sta_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values gen
head(Sta_lcm)
summary(Sta_lcm)	
colnames(Sta_lcm)	


#Stacked without gas
Stn_upload <- data.frame(read.csv(hour_mild_files[12], check.names=FALSE)) 
colnames(Stn_upload) #Taking a look at our colnames
unique(Stn_upload$name) #Make sure right sation is uploaded
summary(Stn_upload)

#Some land cover
Stn_slc <- as.data.frame(Stn_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Stn_slc)
summary(Stn_slc)
colnames(Stn_slc)

#No land cover 	
Stn_nlc <- as.data.frame(Stn_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Stn_nlc)
summary(Stn_nlc)	
colnames(Stn_nlc)

#Land cover majority
Stn_lcm <- as.data.frame(Stn_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Stn_lcm)
summary(Stn_lcm)	
colnames(Stn_lcm)	


#Stoney Moutain 
Sto_upload <- data.frame(read.csv(hour_mild_files[13], check.names=FALSE)) 
colnames(Sto_upload) #Taking a look at our colnames
unique(Sto_upload$name) #Make sure right sation is uploaded

#Some land cover
Sto_slc <- as.data.frame(Sto_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Sto_slc)
summary(Sto_slc)
colnames(Sto_slc)

#No land cover 	
Sto_nlc <- as.data.frame(Sto_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Sto_nlc)
summary(Sto_nlc)	
colnames(Sto_nlc)

#Land cover majority
Sto_lcm <- as.data.frame(Sto_upload)%>%dplyr::select(-c("Var.1", "name", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Sto_lcm)
summary(Sto_lcm)	
colnames(Sto_lcm)



#FOR ALL ARCHIVED DATA 2019-2023#


AData_Path <- "/Users/milsbeary/Desktop/Miles NSERC Alliance Missions /Air Quality Monotoring of Polutents/Land Station/FINAL_STUDY_DS/Data/Archive" #Define data path

Ahour_mild_files <- c(list.files(path=AData_Path, pattern="*.csv", full.names=TRUE)) #Get list of all csv files in the folder
Ahour_mild_files #See list, make sure it is different from the first


#Anzac
Anz_uploadA <- data.frame(read.csv(Ahour_mild_files[1], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit() 
colnames(Anz_uploadA) #Taking a look at our colnames
unique(Anz_uploadA$name) #Make sure right sation is uploaded
#Anz_upload$cloud_fraction

#Some land cover
Anz_slcA <- as.data.frame(Anz_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3", "Land_Cover_majority"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Anz_slcA)
summary(Anz_slcA)	
colnames(Anz_slcA)

#No land cover 	
Anz_nlcA <- as.data.frame(Anz_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow", "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Anz_nlcA)
summary(Anz_nlcA)	
colnames(Anz_nlcA)

#Land cover majority
Anz_lcmA <- as.data.frame(Anz_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm), temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "LW....of.range.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Anz_lcmA)
summary(Anz_lcmA)	
colnames(Anz_lcmA)

#Athabasca 
Ath_uploadA <- data.frame(read.csv(Ahour_mild_files[2], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Ath_uploadA) #Taking a look at our colnames
unique(Ath_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Ath_slcA <- as.data.frame(Ath_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ath_slcA)
summary(Ath_slcA)	
colnames(Ath_slcA)

#No land cover 	
Ath_nlcA <- as.data.frame(Ath_upload)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow",  "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ath_nlcA)
summary(Ath_nlcA)	
colnames(Ath_nlcA)

#Land cover majority
Ath_lcmA <- as.data.frame(Ath_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3"), as.numeric)%>%
			dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Ath_lcmA)
summary(Ath_lcmA)	
colnames(Ath_lcmA)	


#Berta
Ber_uploadA <- data.frame(read.csv(Ahour_mild_files[3], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Ber_uploadA) #Taking a look at our colnames
unique(Ber_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Ber_slcA <- as.data.frame(Ber_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Ber_slcA)
summary(Ber_slcA)
colnames(Ber_slcA)

#No land cover 	
Ber_nlcA <- as.data.frame(Ber_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow", "Land_Cover_majority"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Ber_nlcA)
summary(Ber_nlcA)	
colnames(Ber_nlcA)

#Land cover majority
Ber_lcmA <- as.data.frame(Ber_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "TRS..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CO..ppm.", "CO2..ppm.", "NH3..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Ber_lcmA)
summary(Ber_lcmA)	
colnames(Ber_lcmA)	


#Buffalo
Buf_uploadA <- data.frame(read.csv(Ahour_mild_files[4], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit() 
colnames(Buf_uploadA) #Taking a look at our colnames
unique(Buf_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Buf_slcA <- as.data.frame(Buf_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Buf_slcA)
summary(Buf_slcA)
colnames(Buf_slcA)

#No land cover
Buf_nlcA <- as.data.frame(Buf_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Buf_nlcA)
summary(Buf_nlcA)	
colnames(Buf_nlcA)

#Land cover majority
Buf_lcmA <- as.data.frame(Buf_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			  mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			  mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb.", "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Buf_lcmA)
summary(Buf_lcmA)	
colnames(Buf_lcmA)	


#Conklin 
Con_uploadA <- data.frame(read.csv(Ahour_mild_files[5], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Con_uploadA) #Taking a look at our colnames
unique(Con_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Con_slcA <- as.data.frame(Con_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Con_slcA)
summary(Con_slcA)
colnames(Con_slcA)

#No land cover 	
Con_nlcA <- as.data.frame(Con_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Con_nlcA)
summary(Con_nlcA)	
colnames(Con_nlcA)

#Land cover majority
Con_lcmA <- as.data.frame(Con_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Con_lcmA)
summary(Con_lcmA)	
colnames(Con_lcmA)	


#Janvier
Jan_uploadA <- data.frame(read.csv(Ahour_mild_files[6], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Jan_uploadA) #Taking a look at our colnames
unique(Jan_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Jan_slcA <- as.data.frame(Jan_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Jan_slcA)
summary(Jan_slcA)
colnames(Jan_slcA)

#No land cover 	
Jan_nlcA <- as.data.frame(Jan_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Jan_nlcA)
summary(Jan_nlcA)	
colnames(Jan_nlcA)

#Land cover majority
Jan_lcmA <- as.data.frame(Jan_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "SR.O3",  "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Jan_lcmA)
summary(Jan_lcmA)	
colnames(Jan_lcmA)	


#Lower camp
Low_uploadA <- data.frame(read.csv(Ahour_mild_files[7], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()  
colnames(Low_uploadA) #Taking a look at our colnames
unique(Low_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Low_slcA <- as.data.frame(Low_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Low_slcA)
summary(Low_slcA)
colnames(Low_slcA)

#No land cover 	
Low_nlcA <- as.data.frame(Low_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Low_nlcA)
summary(Low_nlcA)	
colnames(Low_nlcA)

#Land cover majority
Low_lcmA <- as.data.frame(Low_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Low_lcmA)
summary(Low_lcmA)	
colnames(Low_lcmA)


#Mannix 
Man_uploadA <- data.frame(read.csv(Ahour_mild_files[8], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()  
colnames(Man_uploadA) #Taking a look at our colnames
unique(Man_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Man_slcA <- as.data.frame(Man_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Man_slcA)
summary(Man_slcA)
colnames(Man_slcA)

#No land cover 	
Man_nlcA <- as.data.frame(Man_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Man_nlcA)
summary(Man_nlcA)	
colnames(Man_nlcA)

#Land cover majority
Man_lcmA <- as.data.frame(Man_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Man_lcmA)
summary(Man_lcmA)	
colnames(Man_lcmA)	


#Mildred 
Mil_uploadA <- data.frame(read.csv(Ahour_mild_files[9], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Mil_uploadA) #Taking a look at our colnames
unique(Mil_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Mil_slcA <- as.data.frame(Mil_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Mil_slcA)
summary(Mil_slcA)
colnames(Mil_slcA)

#No land cover 	
Mil_nlcA <- as.data.frame(Mil_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Mil_nlcA)
summary(Mil_nlcA)	
colnames(Mil_nlcA)

#Land cover majority
Mil_lcmA <- as.data.frame(Mil_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			  mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "H2S..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Mil_lcmA)
summary(Mil_lcmA)	
colnames(Mil_lcmA)	


#Patricia 
Pat_uploadA <- data.frame(read.csv(Ahour_mild_files[10], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Pat_uploadA) #Taking a look at our colnames
unique(Pat_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Pat_slcA <- as.data.frame(Pat_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Pat_slcA)
summary(Pat_slcA)
colnames(Pat_slcA)

#No land cover 	
Pat_nlcA <- as.data.frame(Pat_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Pat_nlcA)
summary(Pat_nlcA)	
colnames(Pat_nlcA)

#Land cover majority
Pat_lcmA <- as.data.frame(Pat_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "NH3..ppb.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.",  "SR.O3"), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Pat_lcmA)
summary(Pat_lcmA)	
colnames(Pat_lcmA)	


#Stacked with gas 
Sta_uploadA <- data.frame(read.csv(Ahour_mild_files[11], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()  
colnames(Sta_uploadA) #Taking a look at our colnames
unique(Sta_uploadA$name) #Make sure right sation is uploaded
#summary(Sta_uploadA)

#Some land cover
Sta_slcA <- as.data.frame(Sta_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values generated by the Zs	
head(Sta_slcA)
summary(Sta_slcA)
colnames(Sta_slcA)

#No land cover 	
Sta_nlcA <- as.data.frame(Sta_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values generated by the Zs
head(Sta_nlcA)
summary(Sta_nlcA)	
colnames(Sta_nlcA)

#Land cover majority
Sta_lcmA <- as.data.frame(Sta_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))%>%
			 select(where(~ all(!is.na(.)))) #Remove columns with NA values if they exist
			 #na.omit() #Remove all NA values gen
head(Sta_lcmA)
summary(Sta_lcmA)	
colnames(Sta_lcmA)	


#Stacked without gas
Stn_uploadA <- data.frame(read.csv(Ahour_mild_files[12], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Stn_uploadA) #Taking a look at our colnames
unique(Stn_uploadA$name) #Make sure right sation is uploaded
#summary(Stn_uploadA)

#Some land cover
Stn_slcA <- as.data.frame(Stn_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Stn_slcA)
summary(Stn_slcA)
colnames(Stn_slcA)

#No land cover 	
Stn_nlcA <- as.data.frame(Stn_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Stn_nlcA)
summary(Stn_nlcA)	
colnames(Stn_nlcA)

#Land cover majority
Stn_lcmA <- as.data.frame(Stn_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Stn_lcmA)
summary(Stn_lcmA)	
colnames(Stn_lcmA)	


#Stoney Moutain 
Sto_uploadA <- data.frame(read.csv(Ahour_mild_files[13], check.names=FALSE))%>%
			  filter(!if_any(everything(), ~ grepl("Z", .)))%>%na.omit()   
colnames(Sto_uploadA) #Taking a look at our colnames
unique(Sto_uploadA$name) #Make sure right sation is uploaded

#Some land cover
Sto_slcA <- as.data.frame(Sto_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			 mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)#%>%
			 #na.omit() #Remove all NA values generated by the Zs	
head(Sto_slcA)
summary(Sto_slcA)
colnames(Sto_slcA)

#No land cover 	
Sto_nlcA <- as.data.frame(Sto_uploadA)%>%dplyr::select(-c("Var.1", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15", "Land_Cover_majority"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values generated by the Zs
head(Sto_nlcA)
summary(Sto_nlcA)	
colnames(Sto_nlcA)

#Land cover majority
Sto_lcmA <- as.data.frame(Sto_uploadA)%>%dplyr::select(-c("Var.1", "name", "Land_Cover_0", "Land_Cover_1", "Land_Cover_2", "Land_Cover_3", "Land_Cover_4", "Land_Cover_5", "Land_Cover_6", "Land_Cover_7", "Land_Cover_8", "Land_Cover_9", "Land_Cover_10", "Land_Cover_11", "Land_Cover_12", "Land_Cover_13", "Land_Cover_14", "Land_Cover_15"))%>%
			 mutate(day_night = as.character(day_night), holidays = as.character(holidays), yyyy.MM.dd.HH.mm = as.character(yyyy.MM.dd.HH.mm),  temperature_inversion = as.character(temperature_inversion))%>%
			mutate_at(c("AT..C.", "CH4..ppm.", "RH....", "SO2..ppb.", "WD..deg.", "WD_STD..deg.", "WS..km.h.", "WS_STD..km.h.", "BP_2..mB.", "DEW_2..C.", "PAR_16..umol.m.2.s.1.", "SR_29..W.m2.", "VW20..km.h.", "VW20_STD..km.h.", "GR..W.m2.", "CH4..ppm.", "NOX..ppb.", "O3..ppb.", "PM2.5..ug.m3.", "SR.O3", "CO2..ppm.", "CO..ppm.", "LW....of.range.", "TRS..ppb."), as.numeric)%>%
			 dplyr::select(-c("land_cover_water", "land_cover_trees", "land_cover_grass", "land_cover_flooded_vegetation", "land_cover_crops", "land_cover_shrub_and_scrub", "land_cover_built.up_area", "land_cover_bare_ground", "land_cover_snow"))#%>%
			 #na.omit() #Remove all NA values gen
head(Sto_lcmA)
summary(Sto_lcmA)	
colnames(Sto_lcmA)







